services:
  php:
    container_name: php_app
    build:
      context: .
      target: php_fpm_prod
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker/php/env.ini:/usr/local/etc/php/conf.d/env.ini
    environment:
      APP_ENV: prod
      APP_DEBUG: false
      COMMAND: php-fpm
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    env_file:
      - .env
    command: >
      bash -c "cd /var/www/html
      && composer install --no-dev --no-scripts --no-cache --prefer-dist --no-progress
      && php-fpm"
    deploy:
      resources:
        limits:
          memory: 1024M
    stdin_open: true
    ports: ["9000:9000"]

  nginx:
      container_name: nginx_app
      image: nginx:latest
      ports:
          - '8080:80'
      volumes:
          - ./:/var/www/html
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
